@rem = ' vim: set filetype=perl: ';
@rem = ' --*-Perl-*-- ';
@rem = '
@echo off
setlocal
set PATH=%~dp0\perl\bin;%~dp0\bin;%PATH%
perl -w "%~f0" %*
exit /B %ERRORLEVEL%
';

# StorScore
#
# Copyright (c) Microsoft Corporation
#
# All rights reserved. 
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

use strict;
use warnings;

use File::Basename;
use English;

my $script_name = basename( $PROGRAM_NAME );
my $script_dir = dirname( $PROGRAM_NAME );

unless( scalar @ARGV == 1 )
{
    warn "usage: $script_name OUTFILE\n";
    exit(-1);
}

my $outfile = "$script_dir\\$ARGV[0]";

sub my_exec
{
    my $cmd = shift;
    
    system( "echo TEST_BEGIN >> $outfile" );
    system( "echo $cmd >> $outfile" );

    system( "$cmd >> $outfile 2>&1" );

    system( "echo TEST_END >> $outfile" );
    system( "echo. >> $outfile" );
}

sub run_one
{
    my $args = shift;

    my $common_args;
    $common_args .= "--target=1234 ";
    $common_args .= "--pretend ";
    $common_args .= "--verbose ";
    $common_args .= "--noprompt ";

    foreach my $target_type ( qw( auto ssd hdd error ) )
    {
        foreach my $recipe ( undef, 'recipes\\corners.rcp' )
        {
            my $cmd = "storscore.cmd $common_args ";

            $cmd .= "--target_type=$target_type ";
            $cmd .= "--recipe=$recipe " if defined $recipe;

            my_exec( "$cmd $args" );
        }
    }
}

unlink( $outfile );
chdir( ".." );
    
# Preserve existing results directory
rename( "results", "results.orig" );

run_one( "" );
run_one( "--this_flag_does_not_exist" );
run_one( "--initialize" );
run_one( "--noinitialize" );
run_one( "--precondition" );
run_one( "--noprecondition" );
run_one( "--raw_disk" );
run_one( "--active_range=0" );
run_one( "--active_range=1" );
run_one( "--active_range=50" );
run_one( "--active_range=100" );
run_one( "--active_range=110" );
run_one( "--partition_bytes=1000000000" );
run_one( "--partition_bytes=1000000000 --raw_disk" );
run_one( "--demo_mode" );
run_one( "--test_id=regr" );
run_one( "--test_id_prefix=regr" );
run_one( "--nocollect_smart" );
run_one( "--nocollect_logman" );
run_one( "--nocollect_power" );
run_one( "--start_on_step=2" );
run_one( "--stop_on_step=2" );
run_one( "--test_time_override=42" );
run_one( "--warmup_time_override=42" );
run_one( "--compressibility=0" );
run_one( "--compressibility=1" );
run_one( "--compressibility=20" );
run_one( "--compressibility=80" );
run_one( "--compressibility=99" );
 
# Restore original results directory
system( "rmdir /S /Q results >NUL 2>&1" );
rename( "results.orig", "results" );

# Post process output file to remove noise
rename( $outfile, "$outfile.orig" );

open( my $in, "<$outfile.orig" );
open( my $out, ">$outfile" );

while( my $line = <$in> )
{
    # Remove random temp file names
    $line =~ s/AppData\\\S*//;

    # Remove ETA info
    $line =~ s/\d{2}:\d{2}:\d{2} (AM|PM)//g;

    # Remove time from autogenerated results dir
    if( $line =~ /results/ )
    {
        $line =~ s/-\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}//;
    }

    # Remove "Done" line with overall runtime
    $line =~ s/^Done.*//;

    print $out $line;
}

close $in;
close $out;

unlink( "$outfile.orig" );

print "Done! Diff $outfile against another run.\n";
